context:
  version: "21.2.7"

package:
  name: schematics-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@angular-devkit/schematics-cli/-/schematics-cli-${{ version }}.tgz
  sha256: f98fb279131dc6e76de7f94936a449fdecef2bfafbd8f85b927c4e1a0a25f8a3

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - schematics --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Executable for running a Schematic.
  homepage: https://github.com/angular/angular-cli
  repository: https://github.com/angular/angular-cli

extra:
  recipe-maintainers:
    - danielnachun
