context:
  version: "22.0.7"

package:
  name: schematics-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@angular-devkit/schematics-cli/-/schematics-cli-${{ version }}.tgz
  sha256: 3a0d27eac2c054ebd9a5c5297d5869e4235e0b507327322cde727358dcf511be

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - schematics --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Executable for running a Schematic.
  homepage: https://github.com/angular/angular-cli
  repository: https://github.com/angular/angular-cli

extra:
  recipe-maintainers:
    - danielnachun
